WebApp/Controllers/AuthController.cs
using System.Security.Claims;
using AutoMapper;
using Data.Dto;
using Data.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;

namespace WebApp.Controllers;

public class AuthController : Controller
{
    private readonly IUserServices _userServices;
    private readonly IMapper _mapper;

    public AuthController(IUserServices userServices, IMapper mapper)
    {
        _userServices = userServices;
        _mapper = mapper;
    }

    public IActionResult Login(string returnUrl = "/Home/Index")
    {
        return View(new LoginVM { ReturnUrl = returnUrl });
    }

    public async Task<IActionResult> LoginAction(LoginVM loginVm)
    {
        var claims = await _userServices.LoginCookie(loginVm.Username, loginVm.Password);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claims.claimsIdentity), claims.authProperties);

        HttpContext.Session.SetString("username", loginVm.Username);

        return Redirect(loginVm.ReturnUrl);
    }

    public IActionResult Register()
    {
        return View();
    }

    public async Task<IActionResult> RegisterAction(RegisterVM vm)
    {
        await _userServices.CreateUser(_mapper.Map<NewUserDto>(vm));
        return Redirect(nameof(Login));
    }


    public IActionResult Logout(string redirectUrl = "/Home/Index")
    {
        HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return Redirect(redirectUrl);
    }

    public IActionResult AccessDenied()
    {
        return View();
    }
}

WebApp/Controllers/BudgetController.cs
using AutoMapper;
using Data.Models;
using Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize]
public class BudgetController : Controller
{
    private readonly IBudgetService _budgetService;
    private readonly IUserManagementService _userServices;
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;

    public BudgetController(IBudgetService budgetService, IMapper mapper, ICategoryService categoryService,
        IUserManagementService userServices)
    {
        _budgetService = budgetService;
        _mapper = mapper;
        _categoryService = categoryService;
        _userServices = userServices;
    }

    public async Task<IActionResult> Budgets()
    {
        var guid = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value;
        if (guid == null)
            return BadRequest("Guid can't be null");

        var budgets = await _budgetService.GetAll(Guid.Parse(guid));
        var vm = _mapper.Map<List<BudgetVM>>(budgets);
        return View(vm);
    }

    public async Task<IActionResult> EditBudget(string guid)
    {
        var budget = await _budgetService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<BudgetVM>(budget);
        return View(vm);
    }

    public IActionResult CreateBudget()
    {
        return View();
    }

    public async Task<IActionResult> CreateBudgetAction(BudgetVM newBudget)
    {
        var budget = _mapper.Map<Budget>(newBudget);

        budget.Category = await _categoryService.Get(Guid.Parse(newBudget.CategoryGuid));
        budget.User = await _userServices.GetUser(HttpContext.GetUserGuid());

        await _budgetService.Create(budget);
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> EditBudgetAction(BudgetVM updatedBudget)
    {
        var budget = _mapper.Map<Budget>(updatedBudget);
        
        budget.Category = await _categoryService.Get(Guid.Parse(updatedBudget.CategoryGuid));
        budget.CategoryId = budget.Category.Idcategory;
        budget.User = await _userServices.GetUser(HttpContext.GetUserGuid());
        budget.UserId = budget.User.Iduser;
        
        await _budgetService.Edit(Guid.Parse(updatedBudget.Guid), budget);
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> DeleteBudget(string guid)
    {
        await _budgetService.Delete(Guid.Parse(guid));
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> DetailsBudget(string guid)
    {
        if (string.IsNullOrEmpty(guid))
            return BadRequest("Budget GUID is required");

        var budget = await _budgetService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<BudgetVM>(budget);
        return View(vm);
    }
}

WebApp/Controllers/IncomeController.cs
using AutoMapper;
using Data.Models;
using Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize]
public class IncomeController : Controller
{
    private readonly IIncomeService _incomeService;
    private readonly IMapper _mapper;
    private readonly IUserServices _userServices;

    public IncomeController(IIncomeService incomeService, IMapper mapper, IUserServices userServices)
    {
        _incomeService = incomeService;
        _mapper = mapper;
        _userServices = userServices;
    }

    public async Task<IActionResult> Incomes()
    {
        var guid = HttpContext.GetUserGuid();

        var incomes = await _incomeService.GetAll(guid);
        var vms = _mapper.Map<List<IncomeVM>>(incomes);
        return View(vms);
    }

    public async Task<IActionResult> EditIncome(string guid)
    {
        var income = await _incomeService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<IncomeVM>(income);
        return View(vm);
    }

    public IActionResult CreateIncome()
    {
        return View(new IncomeVM());
    }

    public async Task<IActionResult> CreateIncomeAction(IncomeVM incomeVm)
    {
        var newIncome = _mapper.Map<Income>(incomeVm);

        var guid = HttpContext.GetUserGuid();
        var user = await _userServices.GetUser(guid);
        newIncome.UserId = user.Iduser;

        await _incomeService.Create(newIncome);
        return Redirect(nameof(Incomes));
    }

    public async Task<IActionResult> EditIncomeAction(IncomeVM incomeVm)
    {
        var incomeUpdate = _mapper.Map<Income>(incomeVm);
        await _incomeService.Update(Guid.Parse(incomeVm.Guid), incomeUpdate);
        return Redirect(nameof(Incomes));
    }

    public async Task<IActionResult> DeleteIncome(string guid)
    {
        await _incomeService.Delete(Guid.Parse(guid));
        return Redirect(nameof(Incomes));
    }
}

WebApp/Controllers/UserController.cs
using AutoMapper;
using Data.Dto;
using Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize]
public class UserController : Controller
{
    private readonly IUserManagementService _userManagementService;
    private readonly IProfileService _profileService;
    private readonly IMapper _mapper;

    public UserController(IUserManagementService userManagementService, IProfileService profileService, IMapper mapper)
    {
        _userManagementService = userManagementService;
        _profileService = profileService;
        _mapper = mapper;
    }

    [Authorize]
    public async Task<IActionResult> Account(string guid)
    {
        if (string.IsNullOrEmpty(guid))
        {
            guid = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value;
            if (guid == null)
                return BadRequest("User not found");
        }

        var user = await _userManagementService.GetUser(Guid.Parse(guid));
        var userDto = _mapper.Map<UserDto>(user);
        var userVm = _mapper.Map<UserVM>(userDto);
        return View(userVm);
    }

    [Authorize]
    public async Task<IActionResult> EditUser([FromBody] UserDto dto)
    {
        var userGuid = Guid.Parse(HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value);
        await _userManagementService.EditUser(userGuid, dto);
        return Ok();
    }

    [Authorize]
    public async Task<IActionResult> UpdateProfilePicture(IFormFile profilePicture)
    {
        var userGuid = Guid.Parse(HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value);

        if (profilePicture == null || profilePicture.Length == 0)
            return BadRequest("Invalid file");

        var filePath = Path.Combine("wwwroot", "images", "profile_pictures", $"{userGuid}_{profilePicture.FileName}");
        using (var stream = new FileStream(filePath, FileMode.Create))
        {
            await profilePicture.CopyToAsync(stream);
        }

        await _profileService.UpdateProfilePicture(userGuid, $"/images/profile_pictures/{userGuid}_{profilePicture.FileName}");
        return RedirectToAction("Account");
    }
}

WebApp/Views/Shared/_Layout.cshtml
@using Azure.Core
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <style>
        .badge {
            padding: 5px 10px;
            border-radius: 50%;
            background-color: red;
            color: white;
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @{
                var user = this.ViewContext.HttpContext.User;
                bool loggedIn = false;
                string username = "";
                if (user != null && !string.IsNullOrEmpty(user.Identity.Name))
                {
                    loggedIn = true;
                    username = user.Identity.Name;
                }

                string? guid = ViewContext.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value;
            }
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Budget Manager</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (loggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Categories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Income" asp-action="Incomes">Incomes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Budget" asp-action="Budgets">Budget</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Savings" asp-action="Savings">Savings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Expenses">Expense</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav flex-grow-1">
                    <div class="m-auto">
                    </div>
                    @if (loggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark d-block" href="@Url.Action("Index", "Notifications")">
                                <span id="notificationCount" class="badge badge-danger">0</span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-bell" viewBox="0 0 16 16">
                                    <path
                                        d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2M8 1.918l-.797.161A4 4 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4 4 0 0 0-3.203-3.92zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5 5 0 0 1 13 6c0 .88.32 4.2 1.22 6"/>
                                </svg>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="@Url.Action("Account", "User", new { guid })">@username</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="@Url.Action("Logout", "Auth", new { redirectUrl = Context.Request.Path + Context.Request.QueryString })">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="@Url.Action("Login", "Auth", new { returnUrl = Context.Request.Path + Context.Request.QueryString })">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth"
                               asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

@if ((string)ViewData["title"] == "Home Page")
{
    <div class="main-container">
        <main role="main" class="background container">
            @RenderBody()
        </main>
    </div>
}
else
{
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
}
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Fran Cvok - Dominik Despot - Luka Petrečija - Algebra - <a asp-area="" asp-controller="Home"
                                                                                 asp-action="Privacy">Privacy</a>
    </div>
</footer>



<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script>
    const input = document.querySelector("input[name='query']");
    const elms = document.getElementsByClassName("link-btn")
    for (let i = 0; i < elms.length; i++) {
        elms[i].addEventListener("click", function () {
            input.value = elms[i].innerText + "=";
        });

    }

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.11/signalr.min.js"></script>
@if (loggedIn)
{
    <script type="module">
    import {NotificationService} from "/js/NotificationService.js";
    document.addEventListener("DOMContentLoaded", () => {
        if (!window.notificationService) {
            window.notificationService = new NotificationService("/NotificationsSocket", "notificationCount");
        } 
    });
</script>
}
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>