WebApp/Controllers/BudgetController.cs
using AutoMapper;
using Data.Models;
using Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize]
public class BudgetController : Controller
{
    private readonly IBudgetService _budgetService;
    private readonly IUserManagementService _userServices;
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;

    public BudgetController(IBudgetService budgetService, IMapper mapper, ICategoryService categoryService,
        IUserManagementService userServices)
    {
        _budgetService = budgetService;
        _mapper = mapper;
        _categoryService = categoryService;
        _userServices = userServices;
    }

    public async Task<IActionResult> Budgets()
    {
        var guid = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserGuid")?.Value;
        if (guid == null)
            return BadRequest("Guid can't be null");

        var budgets = await _budgetService.GetAll(Guid.Parse(guid));
        var vm = _mapper.Map<List<BudgetVM>>(budgets);
        return View(vm);
    }

    public async Task<IActionResult> EditBudget(string guid)
    {
        var budget = await _budgetService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<BudgetVM>(budget);
        return View(vm);
    }

    public IActionResult CreateBudget()
    {
        return View();
    }

    public async Task<IActionResult> CreateBudgetAction(BudgetVM newBudget)
    {
        var budget = _mapper.Map<Budget>(newBudget);

        budget.Category = await _categoryService.Get(Guid.Parse(newBudget.CategoryGuid));
        budget.User = await _userServices.GetUser(HttpContext.GetUserGuid());

        await _budgetService.Create(budget);
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> EditBudgetAction(BudgetVM updatedBudget)
    {
        var budget = _mapper.Map<Budget>(updatedBudget);
        
        budget.Category = await _categoryService.Get(Guid.Parse(updatedBudget.CategoryGuid));
        budget.CategoryId = budget.Category.Idcategory;
        budget.User = await _userServices.GetUser(HttpContext.GetUserGuid());
        budget.UserId = budget.User.Iduser;
        
        await _budgetService.Edit(Guid.Parse(updatedBudget.Guid), budget);
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> DeleteBudget(string guid)
    {
        await _budgetService.Delete(Guid.Parse(guid));
        return Redirect(nameof(Budgets));
    }

    public async Task<IActionResult> DetailsBudget(string guid)
    {
        if (string.IsNullOrEmpty(guid))
            return BadRequest("Budget GUID is required");

        var budget = await _budgetService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<BudgetVM>(budget);
        return View(vm);
    }
}

WebApp/Controllers/CategoryController.cs
using AutoMapper;
using Data.Models;
using Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize]
public class CategoryController : Controller
{
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;

    public CategoryController(ICategoryService categoryService, IMapper mapper)
    {
        _categoryService = categoryService;
        _mapper = mapper;
    }

    public async Task<IActionResult> Categories()
    {
        var guid = HttpContext.GetUserGuid();
        var categories = await _categoryService.GetAll(guid);
        var vm = _mapper.Map<List<CategoryVM>>(categories);
        return View(vm);
    }

    public IActionResult CreateCategory()
    {
        return View();
    }

    public async Task<IActionResult> CreateCategoryAction(CategoryVM newCate)
    {
        var newCategory = _mapper.Map<Category>(newCate);
        await _categoryService.Create(newCategory);
        return Redirect(nameof(Categories));
    }

    public async Task<IActionResult> EditCategory(string guid)
    {
        var category = await _categoryService.Get(Guid.Parse(guid));
        var vm = _mapper.Map<CategoryVM>(category);

        return View(vm);
    }

    public async Task<IActionResult> EditCategoryAction(CategoryVM newCate)
    {
        var newCategory = _mapper.Map<Category>(newCate);
        newCategory.Guid = Guid.Parse(newCate.Guid);
        await _categoryService.Edit(newCategory);
        return Redirect(nameof(Categories));
    }

    public async Task<IActionResult> DeleteCategory(string guid)
    {
        await _categoryService.Delete(Guid.Parse(guid));
        return Redirect(nameof(Categories));
    }

    public async Task<IActionResult> CategoryProps()
    {
        var userGuid = HttpContext.GetUserGuid();
        var categories = await _categoryService.GetAll(userGuid);
        var props = categories.Select(c => new PropDto
        {
            Text = c.CategoryName,
            Value = c.Guid.ToString(),
        }).ToList();

        return Json(props);
    }
}

WebApp/Views/Budget/Budgets.cshtml
@model IEnumerable<BudgetVM>

@{
    ViewData["Title"] = "Budgets";
}

<h1 class="mb-3">Budgets</h1>
<a class="btn btn-success mb-3" asp-action="CreateBudget">Create new budget</a>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td class="d-flex gap-3">
                    <a class="btn btn-primary" href="@Url.ActionLink("EditBudget", "Budget", new { guid = item.Guid })">
                        Edit
                    </a>
                    <a class="btn btn-danger"
                       href="@Url.ActionLink("DeleteBudget", "Budget", new { guid = item.Guid })"
                       onclick="return confirmDelete(event)"> Delete </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        document.querySelectorAll('.btn-danger').forEach(button => {
            button.addEventListener('click', function (event) {
                event.stopPropagation();
            });
        });

        function confirmDelete(event) {
            if (!confirm("Are you sure you want to delete this budget?")) {
                event.preventDefault();
                return false;
            }
            return true;
        }
    </script>
}

WebApp/Views/Budget/CreateBudget.cshtml
@using Data.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BudgetVM

@{
    ViewData["Title"] = "CreateBudget";
}

<h1>CreateBudget</h1>

<hr/>
<div class="row mb-3">
    <div class="col-md-4">
        <form asp-action="CreateBudgetAction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sum" class="control-label"></label>
                <input asp-for="Sum" class="form-control"/>
                <span asp-validation-for="Sum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryGuid" class="control-label"></label>
                <select asp-for="CategoryGuid" id="dropdown" class="form-control"></select>
                <span asp-validation-for="CategoryGuid" class="text-danger"></span>
            </div> 
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary"/>
                <a class="btn btn-danger" asp-action="Budgets">Cancel</a>
            </div>
        </form>
    </div>
</div>

<script>
   document.addEventListener("DOMContentLoaded", function() {
    const dropdown = document.getElementById("dropdown");

    function populateDropdown(items) {
        const option = document.createElement("option");
        option.value = undefined 
        option.textContent = ""
        dropdown.appendChild(option);
        
        items.forEach(item => {
            const option = document.createElement("option");
            option.value = item.value;
            option.textContent = item.text;
            dropdown.appendChild(option);
        });
    }

    fetch('@Url.ActionLink("CategoryProps","Category")')
        .then(response => response.json())
        .then(data => {
            populateDropdown(data);
        })
        .catch(error => {
            console.error("Error fetching items:", error);
        });

});
</script>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebApp/Views/Budget/DeleteBudget.cshtml
@model BudgetVM

@{
    ViewData["Title"] = "DeleteBudget";
}

<h1>DeleteBudget</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BudgetVM</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
    </dl>

    <form asp-action="DeleteBudgetAction">
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Budget/DetailsBudget.cshtml
@model BudgetVM

<h1>Budget Details</h1>

<div class="row">
    <div class="col-md-8">
        <dl class="row">

            <dt class="col-sm-3">Sum</dt>
            <dd class="col-sm-9">@Model.Sum</dd>

            <dt class="col-sm-3">Category</dt>
            <dd class="col-sm-9">@Model.CategoryName</dd>
        </dl>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-6">
        <h3>Budget Representation</h3>
        <canvas id="budgetPieChart"></canvas>
    </div>
    <div class="col-md-6">
        <h3>Status</h3>
        <p>The budget is currently <strong>FULL</strong>.</p>
    </div>
</div>

<a asp-action="Budgets" class="btn btn-primary">Back to List</a>

@section Scripts {
    <script>
        const budgetSum = @Model.Sum;

        const data = {
            labels: ['Remaining', 'User'],
            datasets: [{
                data: [budgetSum, 0],
                backgroundColor: ['#007bff', '#dcdcdc'],
                borderWidth: 1
            }]
        };

        const config = {
            type: 'pie',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'bottom'
                    },
                    tooltip: {
                        callbacks: {
                            label: function (tooltipItem) {
                                return tooltipItem.label + ': ' + tooltipItem.raw + ' €';
                            }
                        }
                    }
                }
            }
        };

        const ctx = document.getElementById('budgetPieChart').getContext('2d');
        new Chart(ctx, config);
    </script>
}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

WebApp/Views/Budget/EditBudget.cshtml
@model BudgetVM

@{
    ViewData["Title"] = "EditBudget";
}

<h1>EditBudget</h1>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBudgetAction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Guid"  hidden/>
            <div class="form-group">
                <label asp-for="Sum" class="control-label"></label>
                <input asp-for="Sum" class="form-control"/>
                <span asp-validation-for="Sum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Category </label>
                <select asp-for="CategoryGuid" id="dropdown" class="form-control"></select>
                <span asp-validation-for="CategoryGuid" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-primary"/>
                <a asp-action="Budgets" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const dropdown = document.getElementById("dropdown");

        function populateDropdown(items) {
            const option = document.createElement("option");
            option.value = undefined
            option.textContent = ""
            dropdown.appendChild(option);

            items.forEach(item => {
                const option = document.createElement("option");
                option.value = item.value;
                option.textContent = item.text;
                if (item.value === '@Model.CategoryGuid') {
                    option.selected = true;
                }
                dropdown.appendChild(option);
            });
        }

        fetch('@Url.ActionLink("CategoryProps", "Category")')
            .then(response => response.json())
            .then(data => {
                populateDropdown(data);
            })
            .catch(error => {
                console.error("Error fetching items:", error);
            });

    });
</script>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}